sudo: false
language: node_js
dist: trusty
matrix:
  include:
  - node_js: 4
  - node_js: 6
    env:
#      - SAUCE=true
  - node_js: stable

# Make sure we have new NPM.
before_install:
  - npm install -g npm

script:
  - cd sig-server && npm i && cd ..
  - npm run lint
  - npm test
  - npm run coverage

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success:
#  - npm run coverage-publish

addons:
  firefox: 'latest'
